# Generated by Django 4.0.6 on 2022-07-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_freepost_freecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freepost',
            name='author',
        ),
    ]
