# Generated by Django 4.0.6 on 2022-07-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_remove_freepost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
