# Generated by Django 4.0.6 on 2022-07-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_freepost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.CharField(choices=[('N', '상관없음'), ('1', '1명'), ('2', '2명'), ('3', '3명'), ('4', '4명'), ('5+', '5명 이상')], default='N', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('N', '상관없음'), ('M', '남자'), ('F', '여자')], default='N', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('N', '자유'), ('M', '전공')], default='N', max_length=100),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
