# Generated by Django 4.0.6 on 2022-07-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_post_count_post_gender_post_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='mode',
            field=models.CharField(choices=[('S', '팝니다'), ('B', '삽니다')], default='S', max_length=100),
        ),
    ]
