# Generated by Django 4.0.6 on 2022-07-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_alter_freepost_mode_alter_post_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.CharField(choices=[('1명', '1명'), ('2명', '2명'), ('3명', '3명'), ('4명', '4명'), ('5명 이상', '5명 이상')], default='1명', max_length=100),
        ),
    ]
