# Generated by Django 4.0.6 on 2022-07-09 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_table'),
        ('projectapp', '0010_alter_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
